MEDICINE_IMAGES_DIR = "medicine-images/"

STRINGS = {
    # First 2 will always be in English
    #*
    "introduction": ". Hey! How can I help you?",
    "wait_while_load": "Please wait while we setup SpotiFind for you. Thank you for your patience.",
    #*
    "transcript_error": "Sorry, could not figure out what you wanted to find.",
    "transcript_success": "Perfect! Let's go find your '{{object}}'.",
    "object_not_found": "The {{object}} cannot be seen. Please move around!",
    "reached_object": "You are now at the {{object}}. Please use your hands to slowly get a feeling of your environment!",
    "move_left_obstacle": "The {{object}} is in front of you, turn left and move forward.",
    "move_right_obstacle": "The {{object}} is in front of you, turn right and move forward.",
    "move_forward": "Please move forward.",
    "move_left": "Turn left.",
    "move_right": "Turn right.",
    "move_back": "Lost the {{object}}. Please move back.",
    
    "pick_up_medicine_bottle": "Please pick up the medicine bottle and rotate it in your hands to confirm.",
}

CLASSES = {
    "medicine": "medicine",
    "person": "person",
    "bicycle": "bicycle",
    "car": "car",
    "motorcycle": "motorcycle",
    "airplane": "airplane",
    "bus": "bus",
    "train": "train",
    "truck": "truck",
    "boat": "boat",
    "traffic light": "traffic light",
    "fire hydrant": "fire hydrant",
    "stop sign": "stop sign",
    "parking meter": "parking meter",
    "bench": "bench",
    "bird": "bird",
    "cat": "cat",
    "dog": "dog",
    "horse": "horse",
    "sheep": "sheep",
    "cow": "cow",
    "elephant": "elephant",
    "bear": "bear",
    "zebra": "zebra",
    "giraffe": "giraffe",
    "backpack": "backpack",
    "umbrella": "umbrella",
    "handbag": "handbag",
    "tie": "tie",
    "suitcase": "suitcase",
    "frisbee": "frisbee",
    "skis": "skis",
    "snowboard": "snowboard",
    "sports ball": "sports ball",
    "kite": "kite",
    "baseball bat": "baseball bat",
    "baseball glove": "baseball glove",
    "skateboard": "skateboard",
    "surfboard": "surfboard",
    "tennis racket": "tennis racket",
    "bottle": "bottle",
    "wine glass": "wine glass",
    "cup": "cup",
    "fork": "fork",
    "knife": "knife",
    "spoon": "spoon",
    "bowl": "bowl",
    "banana": "banana",
    "apple": "apple",
    "sandwich": "sandwich",
    "orange": "orange",
    "brocolli": "brocolli",
    "carrot": "carrot",
    "hot dog": "hot dog",
    "pizza": "pizza",
    "donut": "donut",
    "cake": "cake",
    "chair": "chair",
    "couch": "couch",
    "potted plant": "potted plant",
    "bed": "bed",
    "dining table": "dining table",
    "toilet": "toilet",
    "tv": "tv",
    "laptop": "laptop",
    "mouse": "mouse",
    "remote": "remote",
    "keyboard": "keyboard",
    "cell phone": "cell phone",
    "microwave": "microwave",
    "oven": "oven",
    "toaster": "toaster",
    "sink": "sink",
    "refrigerator": "refrigerator",
    "book": "book",
    "clock": "clock",
    "vase": "vase",
    "scissors": "scissors",
    "teddy bear": "teddy bear",
    "hair dryer": "hair dryer",
    "toothbrush": "toothbrush",
}