AUDIO_PATH = "say.mp3"
MEDICINE_IMAGES_DIR = "medicine-images/"

STRINGS = {
    # First 2 will always be in English
    #*
    "introduction": ". Ahoy! How may I be o' service to ye?",
    "wait_while_load": "Hold yer course while we be settin' up SpotiFind for ye. Thank ye for yer patience, matey.",
    #*
    "transcript_error": "Sorry, could not figure out what you wanted to find.",
    "transcript_success": "Perfect! Let's go find your '{{object}}'.",
    "object_not_found": "The {{object}} cannot be seen. Please move around!",
    "reached_object": "You are now at the {{object}}. Please use your hands to slowly get a feeling of your environment!",
    "move_left_obstacle": "The {{object}} is in front of you, turn left and move forward.",
    "move_right_obstacle": "The {{object}} is in front of you, turn right and move forward.",
    "move_forward": "Please move forward.",
    "move_left": "Turn left.",
    "move_right": "Turn right.",
    "move_back": "Lost the {{object}}. Please move back.",
    
    "pick_up_medicine_bottle": "Please pick up the medicine bottle",
    "rotate_bottle_in_hands": "Rotate the bottle in your hands",
}

PIRATE_STRINGS_EN = {
    "transcript_error": "Shiver me timbers, could not make head nor tail o' what ye be seekin'.",
    "transcript_success": "Avast! We'll be findin' yer '{{object}}', aye?",
    "object_not_found": "The '{{object}}' be nowhere in sight. Best be movin' about, ye landlubber!",
    "reached_object": "Ye've reached the '{{object}}'. Now, use yer hands to get a feel o' yer surroundings, slowly now!",
    "move_left_obstacle": "The '{{object}}' be straight ahead! Turn to port and sail onward.",
    "move_right_obstacle": "The '{{object}}' be straight ahead! Turn to starboard and sail onward.",
    "move_forward": "Set sail and move forward, ye scallywag!",
    "move_left": "Turn to port, ye bilge rat!",
    "move_right": "Turn to starboard, ye swab!",
    "move_back": "Lost the '{{object}}', we have. Best be backin' up, ye scurvy dog!",
    "pick_up_medicine_bottle": "Seize the medicine bottle, ye salty sea dog!",
    "rotate_bottle_in_hands": "Spin the bottle in yer grasp, aye!"
}

CLASSES = {
    "medicine": "medicine",
    "person": "person",
    "bicycle": "bicycle",
    "car": "car",
    "motorcycle": "motorcycle",
    "airplane": "airplane",
    "bus": "bus",
    "train": "train",
    "truck": "truck",
    "boat": "boat",
    "traffic light": "traffic light",
    "fire hydrant": "fire hydrant",
    "stop sign": "stop sign",
    "parking meter": "parking meter",
    "bench": "bench",
    "bird": "bird",
    "cat": "cat",
    "dog": "dog",
    "horse": "horse",
    "sheep": "sheep",
    "cow": "cow",
    "elephant": "elephant",
    "bear": "bear",
    "zebra": "zebra",
    "giraffe": "giraffe",
    "backpack": "backpack",
    "umbrella": "umbrella",
    "handbag": "handbag",
    "tie": "tie",
    "suitcase": "suitcase",
    "frisbee": "frisbee",
    "skis": "skis",
    "snowboard": "snowboard",
    "sports ball": "sports ball",
    "kite": "kite",
    "baseball bat": "baseball bat",
    "baseball glove": "baseball glove",
    "skateboard": "skateboard",
    "surfboard": "surfboard",
    "tennis racket": "tennis racket",
    "bottle": "bottle",
    "wine glass": "wine glass",
    "cup": "cup",
    "fork": "fork",
    "knife": "knife",
    "spoon": "spoon",
    "bowl": "bowl",
    "banana": "banana",
    "apple": "apple",
    "sandwich": "sandwich",
    "orange": "orange",
    "brocolli": "brocolli",
    "carrot": "carrot",
    "hot dog": "hot dog",
    "pizza": "pizza",
    "donut": "donut",
    "cake": "cake",
    "chair": "chair",
    "couch": "couch",
    "potted plant": "potted plant",
    "bed": "bed",
    "dining table": "dining table",
    "toilet": "toilet",
    "tv": "tv",
    "laptop": "laptop",
    "mouse": "mouse",
    "remote": "remote",
    "keyboard": "keyboard",
    "cell phone": "cell phone",
    "microwave": "microwave",
    "oven": "oven",
    "toaster": "toaster",
    "sink": "sink",
    "refrigerator": "refrigerator",
    "book": "book",
    "clock": "clock",
    "vase": "vase",
    "scissors": "scissors",
    "teddy bear": "teddy bear",
    "hair dryer": "hair dryer",
    "toothbrush": "toothbrush",
}